version: '3.8'

services:
  web:
    build: ./padaria
    command: gunicorn padaria.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    expose:
      - 8000
    env_file:
      - ./padaria/padaria/.env
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: