# Generated by Django 5.1.2 on 2024-11-01 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachada', '0003_dados_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('Gerente', 'Gerente'), ('Vendedor', 'Vendedor'), ('Ajudante', 'Ajudante')], max_length=25),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
