# Generated by Django 5.1.2 on 2024-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachada', '0008_alter_produto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.IntegerField(),
        ),
    ]
